### ISSUE TITLE
Encoding and decoding of data to Kafka

### ISSUE THREAD

**Issue by FreddieMatherSmartDCSIT** [xtuml/munin#155]
A very minor issue but needs documenting. 

- To send an event to the kafka AEReception topic the sender must prepend 4 Byte array for the length of the file - the sender is forced to do this and this is also not documented.
- To receive metrics from the Benchmarking topic the receiver must decode the data in a specific way that is not (obviously) documented.

**Comment by cortlandstarrett** [comment]
This was addressed some time ago by a change in the MASL C++ model compiler.
MASL C++ now generates code that operates on native JSON rather than the funky length + string approach.
